print('#'*13)
num = int(input('Digite um numero: '))
print(f'Você digitou {num}!')
print(f'O dobro de {num} é {num*2}!')
print(f'O triplo de {num} é {num*3}!')
print(f'A raiz quadrada de {num} é {num**0.5:.1f}!')