import tkinter as tk
import tkinter.ttk as ttk


class MenuFormula:
    def __init__(self, master=None):
        # build ui
        menu = ttk.Frame(master)

        cadastro = ttk.Frame(menu)
        produto1 = ttk.Frame(cadastro)
        label_1 = ttk.Label(produto1)
        label_1.config(text='Produto 1:  ')
        label_1.pack(side='left')
        entry_1 = ttk.Entry(produto1)
        entry_1.pack(side='left')
        produto1.config(height='200', width='200')
        produto1.pack(side='top')
        peso1 = ttk.Frame(cadastro)
        label_2 = ttk.Label(peso1)
        label_2.config(text='Peso:           ')
        label_2.pack(side='left')
        entry_2 = ttk.Entry(peso1)
        entry_2.pack(side='left')
        peso1.config(height='200', width='200')
        peso1.pack(side='top')

        produto2 = ttk.Frame(cadastro)
        label_1_3 = ttk.Label(produto2)
        label_1_3.config(text='Produto 2:  ')
        label_1_3.pack(side='left')
        entry_1_3 = ttk.Entry(produto2)
        entry_1_3.pack(side='left')
        produto2.config(height='200', width='200')
        produto2.pack(side='top')
        peso2 = ttk.Frame(cadastro)
        label_1_4 = ttk.Label(peso2)
        label_1_4.config(text='Peso:           ')
        label_1_4.pack(side='left')
        entry_1_4 = ttk.Entry(peso2)
        entry_1_4.pack(side='left')
        peso2.config(height='200', width='200')
        peso2.pack(side='top')

        produto3 = ttk.Frame(cadastro)
        label_1_5 = ttk.Label(produto3)
        label_1_5.config(text='Produto 3:  ')
        label_1_5.pack(side='left')
        entry_1_5 = ttk.Entry(produto3)
        entry_1_5.pack(side='left')
        produto3.config(height='200', width='200')
        produto3.pack(side='top')
        peso3 = ttk.Frame(cadastro)
        label_1_6 = ttk.Label(peso3)
        label_1_6.config(text='Peso:           ')
        label_1_6.pack(side='left')
        entry_1_6 = ttk.Entry(peso3)
        entry_1_6.pack(side='left')
        peso3.config(height='200', width='200')
        peso3.pack(side='top')

        produto4 = ttk.Frame(cadastro)
        label_1_7 = ttk.Label(produto4)
        label_1_7.config(text='Produto 4:  ')
        label_1_7.pack(side='left')
        entry_1_7 = ttk.Entry(produto4)
        entry_1_7.pack(side='left')
        produto4.config(height='200', width='200')
        produto4.pack(side='top')
        peso4 = ttk.Frame(cadastro)
        label_1_8 = ttk.Label(peso4)
        label_1_8.config(text='Peso:           ')
        label_1_8.pack(side='left')
        entry_1_8 = ttk.Entry(peso4)
        entry_1_8.pack(side='left')
        peso4.config(height='200', width='200')
        peso4.pack(side='top')

        produto5 = ttk.Frame(cadastro)
        label_1_9 = ttk.Label(produto5)
        label_1_9.config(text='Produto 5:  ')
        label_1_9.pack(side='left')
        entry_1_9 = ttk.Entry(produto5)
        entry_1_9.pack(side='left')
        produto5.config(height='200', width='200')
        produto5.pack(side='top')
        peso5 = ttk.Frame(cadastro)
        label_1_10 = ttk.Label(peso5)
        label_1_10.config(text='Peso:           ')
        label_1_10.pack(side='left')
        entry_1_10 = ttk.Entry(peso5)
        entry_1_10.pack(side='left')
        peso5.config(height='200', width='200')
        peso5.pack(side='top')

        produto6 = ttk.Frame(cadastro)
        label_1_11 = ttk.Label(produto6)
        label_1_11.config(text='Produto 6:  ')
        label_1_11.pack(side='left')
        entry_1_11 = ttk.Entry(produto6)
        entry_1_11.pack(side='left')
        produto6.config(height='200', width='200')
        produto6.pack(side='top')
        peso6 = ttk.Frame(cadastro)
        label_1_12 = ttk.Label(peso6)
        label_1_12.config(text='Peso:           ')
        label_1_12.pack(side='left')
        entry_1_12 = ttk.Entry(peso6)
        entry_1_12.pack(side='left')
        peso6.config(height='200', width='200')
        peso6.pack(side='top')

        produto7 = ttk.Frame(cadastro)
        label_1_13 = ttk.Label(produto7)
        label_1_13.config(text='Produto 7:  ')
        label_1_13.pack(side='left')
        entry_1_13 = ttk.Entry(produto7)
        entry_1_13.pack(side='left')
        produto7.config(height='200', width='200')
        produto7.pack(side='top')
        peso7 = ttk.Frame(cadastro)
        label_1_14 = ttk.Label(peso7)
        label_1_14.config(text='Peso:           ')
        label_1_14.pack(side='left')
        entry_1_14 = ttk.Entry(peso7)
        entry_1_14.pack(side='left')
        peso7.config(height='200', width='200')
        peso7.pack(side='top')

        produto8 = ttk.Frame(cadastro)
        label_1_15 = ttk.Label(produto8)
        label_1_15.config(text='Produto 8:  ')
        label_1_15.pack(side='left')
        entry_1_15 = ttk.Entry(produto8)
        entry_1_15.pack(side='left')
        produto8.config(height='200', width='200')
        produto8.pack(side='top')
        peso8 = ttk.Frame(cadastro)
        label_1_16 = ttk.Label(peso8)
        label_1_16.config(text='Peso:           ')
        label_1_16.pack(side='left')
        entry_1_16 = ttk.Entry(peso8)
        entry_1_16.pack(side='left')
        peso8.config(height='200', width='200')
        peso8.pack(side='top')

        produto9 = ttk.Frame(cadastro)
        label_1_17 = ttk.Label(produto9)
        label_1_17.config(text='Produto 9:  ')
        label_1_17.pack(side='left')
        entry_1_17 = ttk.Entry(produto9)
        entry_1_17.pack(side='left')
        produto9.config(height='200', width='200')
        produto9.pack(side='top')
        peso9 = ttk.Frame(cadastro)
        label_1_18 = ttk.Label(peso9)
        label_1_18.config(text='Peso:           ')
        label_1_18.pack(side='left')
        entry_1_18 = ttk.Entry(peso9)
        entry_1_18.pack(side='left')
        peso9.config(height='200', width='200')
        peso9.pack(side='top')

        produto10 = ttk.Frame(cadastro)
        label_1_19 = ttk.Label(produto10)
        label_1_19.config(text='Produto 10:')
        label_1_19.pack(side='left')
        entry_1_19 = ttk.Entry(produto10)
        entry_1_19.pack(side='left')
        produto10.config(height='200', width='200')
        produto10.pack(side='top')
        peso10 = ttk.Frame(cadastro)
        label_1_20 = ttk.Label(peso10)
        label_1_20.config(text='Peso:           ')
        label_1_20.pack(side='left')
        entry_1_20 = ttk.Entry(peso10)
        entry_1_20.pack(side='left')
        peso10.config(height='200', width='200')
        peso10.pack(side='top')

        soma = ttk.Frame(cadastro)

        separator_1 = ttk.Separator(soma)
        separator_1.config(orient='horizontal')
        separator_1.pack(fill='x', pady='20', side='top')

        label_26 = ttk.Label(soma)
        label_26.config(text='SOMA:         ')
        label_26.pack(side='left')
        entry_26 = ttk.Entry(soma)
        entry_26.pack(side='top')
        soma.config(height='200', width='200')
        soma.pack(pady='10', side='top')
        cadastro.config(height='200', width='200')
        cadastro.pack(padx='20', pady='20', side='left')

        oc = ttk.Frame(menu)
        tonel = ttk.Frame(oc)

        toneladas = ttk.Label(tonel)
        toneladas.config(text='TONELADAS:')
        toneladas.pack(side='top')
        ton = ttk.Entry(tonel)
        ton.pack(pady='10', side='top')
        tonel.config(height='200', width='200')
        tonel.pack(pady='20', side='top')

        volu = ttk.Frame(oc)
        volume = ttk.Label(volu)
        volume.config(text='       VOLUME: \n'
                           '(Uréia/Nitrogenado)')
        volume.pack(side='top')

        radiobutton_y = ttk.Radiobutton(volu)
        radiobutton_y.config(text='SIM')
        radiobutton_y.pack(side='left')

        radiobutton_n = ttk.Radiobutton(volu)
        radiobutton_n.config(text='NÃO')
        radiobutton_n.pack(side='top')

        volu.config(height='200', width='200')
        volu.pack(pady='20', side='top')

        extrap = ttk.Frame(oc)
        pesoex = ttk.Label(extrap)

        pesoex.config(text='PESO EXTRA:')
        pesoex.pack(pady='0', side='top')
        pextra = ttk.Entry(extrap)
        pextra.pack(side='top')
        extrap.config(height='200', width='200')
        extrap.pack(pady='20', side='top')

        botao = ttk.Frame(oc)
        button_1 = ttk.Button(botao)
        button_1.config(cursor='arrow', state='normal', text='OK')
        button_1.pack(ipadx='20', ipady='20', side='bottom')
        botao.config(height='200', width='200')
        botao.pack(pady='20', side='top')

        oc.config(height='200', width='200')
        oc.pack(padx='20', side='left')

        resultado = ttk.Frame(menu)
        resprop = ttk.Frame(resultado)
        label_29 = ttk.Label(resprop)

        label_29.config(text='PRODUTO')
        label_29.pack(ipadx='55', side='left')
        label_30 = ttk.Label(resprop)

        label_30.config(text='PESO')
        label_30.pack(ipadx='35', side='left')
        resprop.config(height='200', width='200')
        resprop.pack(side='top')

        res1 = ttk.Frame(resultado)
        entry_27 = ttk.Entry(res1)
        entry_27.pack(ipadx='10', padx='10', side='left')
        entry_28 = ttk.Entry(res1)
        entry_28.pack(padx='10', side='top')
        res1.config(height='200', width='200')
        res1.pack(pady='5', side='top')

        res2 = ttk.Frame(resultado)
        entry_27_29 = ttk.Entry(res2)
        entry_27_29.pack(ipadx='10', padx='10', side='left')
        entry_28_30 = ttk.Entry(res2)
        entry_28_30.pack(padx='10', side='top')
        res2.config(height='200', width='200')
        res2.pack(pady='5', side='top')

        res3 = ttk.Frame(resultado)
        entry_27_31 = ttk.Entry(res3)
        entry_27_31.pack(ipadx='10', padx='10', side='left')
        entry_28_32 = ttk.Entry(res3)
        entry_28_32.pack(padx='10', side='top')
        res3.config(height='200', width='200')
        res3.pack(pady='5', side='top')

        res4 = ttk.Frame(resultado)
        entry_27_33 = ttk.Entry(res4)
        entry_27_33.pack(ipadx='10', padx='10', side='left')
        entry_28_34 = ttk.Entry(res4)
        entry_28_34.pack(padx='10', side='top')
        res4.config(height='200', width='200')
        res4.pack(pady='5', side='top')

        res5 = ttk.Frame(resultado)
        entry_27_35 = ttk.Entry(res5)
        entry_27_35.pack(ipadx='10', padx='10', side='left')
        entry_28_36 = ttk.Entry(res5)
        entry_28_36.pack(padx='10', side='top')
        res5.config(height='200', width='200')
        res5.pack(pady='5', side='top')

        res6 = ttk.Frame(resultado)
        entry_27_37 = ttk.Entry(res6)
        entry_27_37.pack(ipadx='10', padx='10', side='left')
        entry_28_38 = ttk.Entry(res6)
        entry_28_38.pack(padx='10', side='top')
        res6.config(height='200', width='200')
        res6.pack(pady='5', side='top')

        res7 = ttk.Frame(resultado)
        entry_27_39 = ttk.Entry(res7)
        entry_27_39.pack(ipadx='10', padx='10', side='left')
        entry_28_40 = ttk.Entry(res7)
        entry_28_40.pack(padx='10', side='top')
        res7.config(height='200', width='200')
        res7.pack(pady='5', side='top')

        res8 = ttk.Frame(resultado)
        entry_27_41 = ttk.Entry(res8)
        entry_27_41.pack(ipadx='10', padx='10', side='left')
        entry_28_42 = ttk.Entry(res8)
        entry_28_42.pack(padx='10', side='top')
        res8.config(height='200', width='200')
        res8.pack(pady='5', side='top')

        res9 = ttk.Frame(resultado)
        entry_27_43 = ttk.Entry(res9)
        entry_27_43.pack(ipadx='10', padx='10', side='left')
        entry_28_44 = ttk.Entry(res9)
        entry_28_44.pack(padx='10', side='top')
        res9.config(height='200', width='200')
        res9.pack(pady='5', side='top')

        res10 = ttk.Frame(resultado)
        entry_27_45 = ttk.Entry(res10)
        entry_27_45.pack(ipadx='10', padx='10', side='left')
        entry_28_46 = ttk.Entry(res10)
        entry_28_46.pack(padx='10', side='top')
        res10.config(height='200', width='200')
        res10.pack(pady='5', side='top')

        batidas = ttk.Frame(resultado)

        label_31 = ttk.Label(batidas)
        label_31.config(text='TOTAL DE BATIDAS:')
        label_31.pack(ipadx='10', padx='20', side='top')
        entry_47 = ttk.Entry(batidas)
        entry_47.pack(ipadx='5', ipady='5', side='top')
        batidas.config(height='200', width='200')
        batidas.pack(side='left')

        pesotot = ttk.Frame(resultado)
        label_32 = ttk.Label(pesotot)
        label_32.config(text='PESO TOTAL:')
        label_32.pack(side='top')
        entry_48 = ttk.Entry(pesotot)
        entry_48.pack(ipady='5', side='top')
        pesotot.config(height='200', width='200')
        pesotot.pack(side='top')

        resultado.config(height='200', width='200')
        resultado.pack(side='left')

        menu.config(height='200', width='200')
        menu.pack(side='top')

        # Main widget
        self.mainwindow = menu

    def run(self):
        self.mainwindow.mainloop()


if __name__ == '__main__':
    root = tk.Tk()
    app = MenuFormula(root)
    app.run()
