cbra19 = ('Flamengo', 'Santos', 'Palmeiras', 'Grêmio', 'Athletico P.', 'Sao Paulo', 'Internacional', 'Corinthians', 'Fortaleza', 'Goias', 'Bahia', 'Vasco', 'Atletico MG', 'Fluminense', 'Botafogo', 'Ceara', 'Cruzeiro', 'CSA', 'Chapecoense', 'Avai')
print(f'O campeonato brasileiro: {cbra19}')
print('-'*93)
print(f'Os 5 primeiros são: {cbra19[0:5]}')
print('-'*63)
print(f'Os 4 ultimos são: {cbra19[-4:]}')
print('-'*48)
print('Ordem alfabetica:')
print(sorted(cbra19))
print('-'*93)
print(f"A posição da Chapecoense é {cbra19.index('Chapecoense')+1}º")
print('-'*27)
