from math import radians, sin, cos, tan
angul = float(input('Digite um angulo: '))
print('-='*20)
print(f'O angulo é {angul}')
seno = sin(angul)
cosse = cos(angul)
tange = tan(angul)
print(f'O seno é {seno:.2f}')
print(f'O cosseno é {cosse:.2f}')
print(f'O tangente é {tange:.2f}')
